#!/usr/bin/env bash
#
# Create docker container
# Symlink scripts/build to top level of recipe dir

builders="fedora23-fpm centos7-fpm"
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root_dir="$(dirname $dir)"
for i in $builders; do
  echo "Building Docker container, $i"
  docker build -f "${root_dir}"/dockerfiles/Dockerfile."${i}" -t "$i" .
done
[[ ! -f "${dir}/build" ]] && ln -s "${dir}"/build "${root_dir}"/build
